add AbstractDataset, ArrayDataset and move BostonHousing to new interface
JuliaML/MLDatasets.jl pull request #98
Opened 2022-03-20 12:57 UTC by CarloLucibello

This is a follow-up to #96 and a continuation of the redesign planned in #73, aiming at redesigning only the simple `BostonHousing` dataset for the time being.

`ArrayDataset` is introduced for completeness but not used in `BostonHousing`, I think it is better to have flat structures whenever we can. 

`AbstractDataset` is introduced mainly to provide an informative print of a dataset with zero effort.

I'm struggling with providing a deprecation path using `getproperty(::Type{BostonHousing}, s)`, see discussion below

2022-03-20 12:59 UTC, CarloLucibello commented on src/MLDatasets.jl
> -
these are just moved into the newly created `utils.jl`

2022-03-20 13:00 UTC, CarloLucibello commented on src/containers/cacheddataset.jl
> -CachedDataset(source, cachesize::Int = numobs(source)) = CachedDataset(source, 1:cachesize)
this is definition seems ambiguous with the one above

2022-03-20 13:01 UTC, CarloLucibello commented on src/containers/cacheddataset.jl
> +struct CachedDataset{T, S} <: AbstractDataContainer
I think this was just forgotten, every other container has it

2022-03-20 13:06 UTC, CarloLucibello commented on src/datasets_misc/boston_housing.jl
> +# end
uncommenting in this, I get an error already at object creation, julia tries to access T.name and is rewired here.
```julia
julia> dataset = BostonHousing()
s = :name
Error showing value of type s = :name
ERROR: type BostonHousing has no field name
Stacktrace:
  [1] getproperty(#unused#::s = :name

SYSTEM (REPL): showing an error caused an error
ERROR: type BostonHousing has no field name
Stacktrace:
  [1] getproperty(#unused#::s = :name

SYSTEM (REPL): caught exception of type ErrorException while trying to handle a nested exception; giving up
```

2022-03-20 13:13 UTC, CarloLucibello commented on src/datasets_misc/boston_housing.jl
> +# end
nevermind, there was a silly mistake

2022-03-20 22:05 UTC, darsnack requested changes
I agree that `ArrayDataset` is not necessary and it is better to just use the array directly.

In general, I think we should try to minimize directly reading and writing the files on disk as much as possible. If the low level containers don't automate some of this for us, then they probably won't be useful to users either. We want something like:
```julia
function Iris(; dir = nothing)
  file = datafile("Iris", "iris.data", dir)
  # table should already be cached in memory via DataFrame
  # accessing rows already produces a named tuple of the columns
  # could have TableDataset accept a "colnames" keyword if we want
  # to always have features/targets
  data = TableDataset(file)

  Iris(file, data)
end
```

Maybe we can have it so that
```julia
struct Iris <: AbstractDataset
  # ...
end

# datasets = container + metadata
# interface: get the core container
samples(iris::Iris) = iris.data

# boilerplate
getindex(dataset::AbstractDataset, i) = getobs(samples(dataset), i)
length(dataset::AbstractDataset) = numobs(samples(dataset))
```

2022-04-03 19:29 UTC, darsnack commented
The goal here is to have a unified interface for in-memory table datasets, right? I'm slightly confused what the interface is as per the PR. Perhaps it makes more sense to not have `AbstractDataset` and instead have `SupervisedDataset` which requires the functions `features` and `targets` defined as well as the named tuple `getobs` discussed above?

Sidenote: the fact that Boston Housing or Titanic require a `feature_names` field seems like a strong indicator to me that they should be tables like a `DataFrame` and not auto-convert to arrays.

2022-04-04 13:10 UTC, darsnack requested changes
Looks good to me, but I would suggest dropping the `as_df` keyword for now (reverting to always returning arrays). Maybe we can consider `DataFrame` support a feature for later, so that we don't introduce something into the API now that we need to potentially deprecate.

2022-04-05 06:32 UTC, CarloLucibello commented on src/datasets_misc/mutagenesis.jl
> +    metadata = open(JSON3.read, metadata_path)
I'm not using those containers yet

2022-04-06 05:06 UTC, CarloLucibello commented on src/abstract_dataset.jl
> +Base.length(d::AbstractDataset) = numobs(d.features)
done

2022-04-06 05:35 UTC, CarloLucibello commented
I'm happy with this actually. Unless dealing with very very large tables, we generically want to load tables as dataframes, no point in having lazy wrappers. Also, array representations are not ok in most cases, you lose per-column eltype information and also have to store column names elsewhere. For data wrangling of tabular data, you just want data frames. 
So here I'm just mimicking the `sklearn.dataset` interface and we add on top of that the indexing/getobs interface. 
I think we just want the `as_df` option, and hardly go back, so since it is ready let's just do it.

2022-04-06 06:13 UTC, CarloLucibello commented
Unfortunately, first-time use of `CSV.read` has a lot of compilation overhead:

 ```julia
julia> @time CSV.read("../../datadeps/Iris/iris.data", DataFrame, header=0)
 14.600421 seconds (2.93 M allocations: 129.822 MiB, 99.98% compilation time)
```
So this PR gives
```julia
# MASTER
julia> @time using MLDatasets
  6.931466 seconds (14.01 M allocations: 824.053 MiB, 6.86% gc time, 69.56% compilation time)

julia> @time Iris().features;
 15.290096 seconds (4.65 M allocations: 226.622 MiB, 0.25% gc time, 99.98% compilation time)

julia> @time Iris().features;
  0.000516 seconds (512 allocations: 42.750 KiB)
```
While on master, where `readdlm` is used instead, we have 
```julia
julia> @time using MLDatasets
  6.996220 seconds (14.53 M allocations: 839.009 MiB, 6.59% gc time, 69.33% compilation time)
  
julia> @time Iris.features();
  0.874926 seconds (1.71 M allocations: 95.881 MiB, 5.78% gc time, 99.82% compilation time)

julia> @time Iris.features();
  0.001535 seconds (15.43 k allocations: 461.656 KiB)

2022-04-08 06:09 UTC, CarloLucibello commented
I'm going on and merging this since there are a lot of datasets still to be ported and plenty of time for more discussions and revisiting choices before the next tag. @darsnack if you are unhappy with this design let's continue the discussion in #73 or even better let's open an issue specific to in-memory tabular datasets

2022-04-08 06:09 UTC, merged

2022-04-08 13:55 UTC, darsnack commented
Sounds good, sorry I missed your messages from 2 days ago for some reason. I'll open an issue for further discussion.